name: Docker push nightly

on:
  workflow_dispatch: # Enables the manual "Run workflow" button in GitHub UI

permissions:
  contents: read

jobs:
  publish:
    uses: ./.github/workflows/dockerPublish.yml
    with:
      tag: nightly
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
